"""HTML performance report generation.

Produces a self-contained HTML file with performance metrics, NAV chart,
drawdown chart, factor attribution, and weight history visualization.
All charts are rendered as inline SVG — no external dependencies.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from alpha_holdings.analytics.attribution import AttributionResult
from alpha_holdings.analytics.performance import PerformanceReport


def render_html_report(
    *,
    report: PerformanceReport,
    nav_series: pd.DataFrame,
    attribution: AttributionResult | None = None,
    weight_history: pd.DataFrame | None = None,
    output_path: Path,
) -> Path:
    """Render a self-contained HTML performance report.

    Args:
        report: Computed performance metrics.
        nav_series: DataFrame with date, nav, daily_return, benchmark_return columns.
        attribution: Optional factor attribution results.
        weight_history: Optional DataFrame with date + per-symbol weight columns.
        output_path: Path to write the HTML file.

    Returns:
        Path to the written HTML file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    nav_chart = _render_nav_chart(nav_series)
    drawdown_chart = _render_drawdown_chart(nav_series)
    attribution_section = _render_attribution_section(attribution) if attribution else ""
    weight_section = _render_weight_section(weight_history) if weight_history is not None else ""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Performance Report — {report.portfolio_id}</title>
<style>
{_css()}
</style>
</head>
<body>
<div class="container">
<h1>Performance Report</h1>
<p class="subtitle">{report.portfolio_id} &mdash; {report.start_date} to {report.end_date}</p>

<section class="metrics">
<h2>Summary Metrics</h2>
{_render_metrics_table(report)}
</section>

<section class="chart-section">
<h2>Portfolio NAV</h2>
{nav_chart}
</section>

<section class="chart-section">
<h2>Drawdown</h2>
{drawdown_chart}
</section>

{attribution_section}
{weight_section}

<footer>
<p>Generated by alpha-holdings. Free-data limitations apply.</p>
</footer>
</div>
</body>
</html>"""

    output_path.write_text(html, encoding="utf-8")
    return output_path


# ---------------------------------------------------------------------------
# HTML building blocks
# ---------------------------------------------------------------------------


def _css() -> str:
    return """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #f8f9fa; color: #212529; line-height: 1.5;
}
.container { max-width: 960px; margin: 0 auto; padding: 2rem 1rem; }
h1 { font-size: 1.8rem; margin-bottom: 0.2rem; }
h2 { font-size: 1.3rem; margin: 1.5rem 0 0.8rem; color: #495057; }
.subtitle { color: #6c757d; margin-bottom: 1.5rem; }
table { border-collapse: collapse; width: 100%; margin-bottom: 1rem; }
th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #dee2e6; }
th { background: #e9ecef; font-weight: 600; }
tr:hover { background: #f1f3f5; }
.positive { color: #2b8a3e; }
.negative { color: #c92a2a; }
.chart-section { margin: 2rem 0; }
svg { width: 100%; height: auto; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #dee2e6;
         color: #868e96; font-size: 0.85rem; }
.bar-label { font-size: 0.75rem; fill: #495057; }
.attribution-table td:nth-child(n+2) { text-align: right; }
.attribution-table th:nth-child(n+2) { text-align: right; }
"""


def _render_metrics_table(report: PerformanceReport) -> str:
    rows = report.summary.to_dict(orient="records")
    tbody = ""
    for r in rows:
        metric = _html_escape(str(r["metric"]))
        value = _html_escape(str(r["value"]))
        css_class = ""
        if "%" in value and value != "N/A":
            try:
                num = float(value.replace("%", "").replace(",", ""))
                css_class = (
                    ' class="positive"' if num > 0 else ' class="negative"' if num < 0 else ""
                )
            except ValueError:
                pass
        tbody += f"<tr><td>{metric}</td><td{css_class}>{value}</td></tr>\n"
    return f"<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>{tbody}</tbody></table>"


def _render_nav_chart(nav_series: pd.DataFrame) -> str:
    """Render NAV line chart as inline SVG."""
    df = nav_series.copy()
    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"])
        df = df.sort_values("date").reset_index(drop=True)

    navs = df["nav"].values
    if len(navs) < 2:
        return "<p>Insufficient data for chart.</p>"

    # Chart dimensions
    w, h = 900, 300
    pad_l, pad_r, pad_t, pad_b = 70, 20, 20, 40

    chart_w = w - pad_l - pad_r
    chart_h = h - pad_t - pad_b

    nav_min = float(np.min(navs)) * 0.99
    nav_max = float(np.max(navs)) * 1.01
    nav_range = nav_max - nav_min if nav_max != nav_min else 1.0

    n = len(navs)
    points = []
    for i, val in enumerate(navs):
        x = pad_l + (i / max(n - 1, 1)) * chart_w
        y = pad_t + chart_h - ((float(val) - nav_min) / nav_range) * chart_h
        points.append(f"{x:.1f},{y:.1f}")

    polyline = " ".join(points)

    # Benchmark NAV overlay
    bm_polyline = ""
    if "benchmark_return" in df.columns and df["benchmark_return"].abs().sum() > 0:
        bm_rets = df["benchmark_return"].fillna(0.0).values
        bm_nav = np.ones(len(bm_rets))
        bm_nav[0] = navs[0]
        for i in range(1, len(bm_rets)):
            bm_nav[i] = bm_nav[i - 1] * (1.0 + bm_rets[i])
        bm_points = []
        for i, val in enumerate(bm_nav):
            x = pad_l + (i / max(n - 1, 1)) * chart_w
            y = pad_t + chart_h - ((float(val) - nav_min) / nav_range) * chart_h
            y = max(pad_t, min(pad_t + chart_h, y))
            bm_points.append(f"{x:.1f},{y:.1f}")
        bm_polyline = f'<polyline points="{" ".join(bm_points)}" fill="none" stroke="#868e96" stroke-width="1.5" stroke-dasharray="4,3"/>'

    # Y-axis labels
    y_labels = ""
    for i in range(5):
        val = nav_min + (nav_range * i / 4)
        y = pad_t + chart_h - (i / 4) * chart_h
        y_labels += f'<text x="{pad_l - 8}" y="{y + 4}" text-anchor="end" font-size="11" fill="#6c757d">{val:,.0f}</text>'
        y_labels += f'<line x1="{pad_l}" y1="{y}" x2="{w - pad_r}" y2="{y}" stroke="#e9ecef" stroke-width="1"/>'

    # X-axis labels
    x_labels = ""
    dates = df["date"].values if "date" in df.columns else range(n)
    label_count = min(6, n)
    for i in range(label_count):
        idx = int(i * (n - 1) / max(label_count - 1, 1))
        x = pad_l + (idx / max(n - 1, 1)) * chart_w
        if hasattr(dates[idx], "astype"):
            label = str(pd.Timestamp(dates[idx]).date())
        else:
            label = str(dates[idx])
        x_labels += f'<text x="{x}" y="{h - 5}" text-anchor="middle" font-size="11" fill="#6c757d">{label}</text>'

    legend = ""
    if bm_polyline:
        legend = (
            f'<line x1="{pad_l + 10}" y1="{pad_t + 12}" x2="{pad_l + 30}" y2="{pad_t + 12}" stroke="#228be6" stroke-width="2"/>'
            f'<text x="{pad_l + 35}" y="{pad_t + 16}" font-size="11" fill="#228be6">Portfolio</text>'
            f'<line x1="{pad_l + 110}" y1="{pad_t + 12}" x2="{pad_l + 130}" y2="{pad_t + 12}" stroke="#868e96" stroke-width="1.5" stroke-dasharray="4,3"/>'
            f'<text x="{pad_l + 135}" y="{pad_t + 16}" font-size="11" fill="#868e96">Benchmark</text>'
        )

    return f"""<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg">
{y_labels}
{x_labels}
{bm_polyline}
<polyline points="{polyline}" fill="none" stroke="#228be6" stroke-width="2"/>
{legend}
</svg>"""


def _render_drawdown_chart(nav_series: pd.DataFrame) -> str:
    """Render drawdown area chart as inline SVG."""
    df = nav_series.copy()
    if "date" in df.columns:
        df = df.sort_values("date").reset_index(drop=True)

    navs = df["nav"].values
    if len(navs) < 2:
        return "<p>Insufficient data for chart.</p>"

    # Compute drawdown series
    peak = navs[0]
    drawdowns = []
    for val in navs:
        if val > peak:
            peak = val
        dd = (val - peak) / peak if peak > 0 else 0.0
        drawdowns.append(dd)

    w, h = 900, 200
    pad_l, pad_r, pad_t, pad_b = 70, 20, 15, 40
    chart_w = w - pad_l - pad_r
    chart_h = h - pad_t - pad_b

    dd_min = min(drawdowns) * 1.1 if min(drawdowns) < 0 else -0.01
    dd_max = 0.0
    dd_range = dd_max - dd_min if dd_max != dd_min else 0.01

    n = len(drawdowns)
    # Area fill
    area_points = [f"{pad_l:.1f},{pad_t:.1f}"]
    for i, dd in enumerate(drawdowns):
        x = pad_l + (i / max(n - 1, 1)) * chart_w
        y = pad_t + ((dd_max - dd) / dd_range) * chart_h
        area_points.append(f"{x:.1f},{y:.1f}")
    area_points.append(f"{pad_l + chart_w:.1f},{pad_t:.1f}")

    # Y-axis labels
    y_labels = ""
    for i in range(5):
        val = dd_min + (dd_range * i / 4)
        y = pad_t + chart_h - (i / 4) * chart_h
        y_labels += f'<text x="{pad_l - 8}" y="{y + 4}" text-anchor="end" font-size="11" fill="#6c757d">{val:.1%}</text>'
        y_labels += f'<line x1="{pad_l}" y1="{y}" x2="{w - pad_r}" y2="{y}" stroke="#e9ecef" stroke-width="1"/>'

    # X-axis labels
    x_labels = ""
    dates = df["date"].values if "date" in df.columns else range(n)
    label_count = min(6, n)
    for i in range(label_count):
        idx = int(i * (n - 1) / max(label_count - 1, 1))
        x = pad_l + (idx / max(n - 1, 1)) * chart_w
        if hasattr(dates[idx], "astype"):
            label = str(pd.Timestamp(dates[idx]).date())
        else:
            label = str(dates[idx])
        x_labels += f'<text x="{x}" y="{h - 5}" text-anchor="middle" font-size="11" fill="#6c757d">{label}</text>'

    return f"""<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg">
{y_labels}
{x_labels}
<polygon points="{" ".join(area_points)}" fill="#ffe3e3" stroke="none"/>
<polyline points="{" ".join(area_points[1:-1])}" fill="none" stroke="#c92a2a" stroke-width="1.5"/>
<line x1="{pad_l}" y1="{pad_t}" x2="{w - pad_r}" y2="{pad_t}" stroke="#495057" stroke-width="0.5"/>
</svg>"""


def _render_attribution_section(attr: AttributionResult) -> str:
    """Render factor attribution table and bar chart."""
    if not attr.factors:
        return ""

    # Table
    rows = ""
    for f in attr.factors:
        css = (
            ' class="positive"'
            if f.contribution_ann > 0
            else ' class="negative"'
            if f.contribution_ann < 0
            else ""
        )
        rows += (
            f"<tr><td>{_html_escape(f.name)}</td>"
            f"<td>{f.beta:.4f}</td>"
            f"<td>{f.mean_factor_return_ann:.2%}</td>"
            f"<td{css}>{f.contribution_ann:.2%}</td>"
            f"<td>{f.t_stat:.2f}</td></tr>\n"
        )
    alpha_css = (
        ' class="positive"'
        if attr.alpha_ann > 0
        else ' class="negative"'
        if attr.alpha_ann < 0
        else ""
    )
    rows += (
        f"<tr><td><strong>Alpha</strong></td>"
        f"<td>—</td><td>—</td>"
        f"<td{alpha_css}><strong>{attr.alpha_ann:.2%}</strong></td>"
        f"<td>—</td></tr>\n"
    )

    table = f"""<table class="attribution-table">
<thead><tr><th>Factor</th><th>Beta</th><th>Mean Factor Return (ann.)</th><th>Contribution (ann.)</th><th>t-stat</th></tr></thead>
<tbody>{rows}</tbody>
</table>
<p style="color:#6c757d;font-size:0.85rem;">R² = {attr.r_squared:.4f} &mdash; Residual Vol = {attr.residual_vol_ann:.2%}</p>"""

    # Bar chart
    bar_chart = _render_attribution_bars(attr)

    return f"""<section class="chart-section">
<h2>Factor Attribution</h2>
{table}
{bar_chart}
</section>"""


def _render_attribution_bars(attr: AttributionResult) -> str:
    """Render horizontal bar chart for factor contributions."""
    items = [(f.name, f.contribution_ann) for f in attr.factors]
    items.append(("Alpha", attr.alpha_ann))

    if not items:
        return ""

    w, h_per_bar = 600, 30
    pad_l, pad_r, pad_t = 120, 40, 10
    chart_w = w - pad_l - pad_r
    total_h = pad_t + len(items) * h_per_bar + 10

    vals = [v for _, v in items]
    max_abs = max(abs(v) for v in vals) if vals else 0.01
    if max_abs == 0:
        max_abs = 0.01

    mid_x = pad_l + chart_w / 2
    bars = ""
    for i, (name, val) in enumerate(items):
        y = pad_t + i * h_per_bar + 5
        bar_w = (val / max_abs) * (chart_w / 2)
        color = "#2b8a3e" if val >= 0 else "#c92a2a"

        if val >= 0:
            bars += f'<rect x="{mid_x}" y="{y}" width="{abs(bar_w):.1f}" height="20" fill="{color}" rx="2"/>'
        else:
            bars += f'<rect x="{mid_x + bar_w:.1f}" y="{y}" width="{abs(bar_w):.1f}" height="20" fill="{color}" rx="2"/>'

        bars += f'<text x="{pad_l - 5}" y="{y + 14}" text-anchor="end" class="bar-label">{_html_escape(name)}</text>'
        bars += f'<text x="{mid_x + bar_w + (5 if val >= 0 else -5):.1f}" y="{y + 14}" text-anchor="{"start" if val >= 0 else "end"}" class="bar-label">{val:.2%}</text>'

    # Center line
    bars += f'<line x1="{mid_x}" y1="{pad_t}" x2="{mid_x}" y2="{total_h - 5}" stroke="#495057" stroke-width="1"/>'

    return f'<svg viewBox="0 0 {w} {total_h}" xmlns="http://www.w3.org/2000/svg">{bars}</svg>'


def _render_weight_section(weight_history: pd.DataFrame) -> str:
    """Render portfolio weight evolution as a stacked area chart."""
    if weight_history is None or weight_history.empty:
        return ""

    df = weight_history.copy()
    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"])
        df = df.sort_values("date").reset_index(drop=True)
        dates = df["date"].values
        weight_cols = [c for c in df.columns if c != "date"]
    else:
        dates = list(range(len(df)))
        weight_cols = list(df.columns)

    if not weight_cols or len(df) < 2:
        return ""

    # Limit to top N positions by average weight for readability
    avg_weights = df[weight_cols].mean().sort_values(ascending=False)
    top_n = 10
    top_symbols = avg_weights.head(top_n).index.tolist()
    other_weight = df[[c for c in weight_cols if c not in top_symbols]].sum(axis=1)

    display_cols = top_symbols
    if float(other_weight.sum()) > 0:
        df["Other"] = other_weight
        display_cols = [*top_symbols, "Other"]

    w, h = 900, 300
    pad_l, pad_r, pad_t, pad_b = 70, 120, 20, 40
    chart_w = w - pad_l - pad_r
    chart_h = h - pad_t - pad_b

    n = len(df)
    colors = [
        "#228be6",
        "#40c057",
        "#fab005",
        "#f06595",
        "#7950f2",
        "#15aabf",
        "#ff6b6b",
        "#82c91e",
        "#fd7e14",
        "#495057",
        "#868e96",
    ]

    # Build cumulative stacked areas bottom-up
    areas = ""
    cumulative = np.zeros(n)
    for idx, col in enumerate(display_cols):
        values = df[col].fillna(0.0).values
        prev_cum = cumulative.copy()
        cumulative = cumulative + values
        color = colors[idx % len(colors)]

        # Build polygon points: forward on top, backward on bottom
        top_points = []
        bottom_points = []
        for i in range(n):
            x = pad_l + (i / max(n - 1, 1)) * chart_w
            y_top = pad_t + chart_h - cumulative[i] * chart_h
            y_bot = pad_t + chart_h - prev_cum[i] * chart_h
            top_points.append(f"{x:.1f},{y_top:.1f}")
            bottom_points.append(f"{x:.1f},{y_bot:.1f}")
        bottom_points.reverse()
        polygon = " ".join(top_points + bottom_points)
        areas += f'<polygon points="{polygon}" fill="{color}" opacity="0.7"/>\n'

    # Legend
    legend = ""
    for idx, col in enumerate(display_cols):
        color = colors[idx % len(colors)]
        lx = w - pad_r + 10
        ly = pad_t + idx * 18
        legend += f'<rect x="{lx}" y="{ly}" width="12" height="12" fill="{color}" rx="2"/>'
        legend += f'<text x="{lx + 16}" y="{ly + 10}" font-size="10" fill="#495057">{_html_escape(col)}</text>'

    # Y-axis
    y_labels = ""
    for i in range(5):
        val = i / 4
        y = pad_t + chart_h - val * chart_h
        y_labels += f'<text x="{pad_l - 8}" y="{y + 4}" text-anchor="end" font-size="11" fill="#6c757d">{val:.0%}</text>'
        y_labels += f'<line x1="{pad_l}" y1="{y}" x2="{pad_l + chart_w}" y2="{y}" stroke="#e9ecef" stroke-width="1"/>'

    # X-axis
    x_labels = ""
    label_count = min(6, n)
    for i in range(label_count):
        idx_val = int(i * (n - 1) / max(label_count - 1, 1))
        x = pad_l + (idx_val / max(n - 1, 1)) * chart_w
        if hasattr(dates[idx_val], "astype"):
            label = str(pd.Timestamp(dates[idx_val]).date())
        else:
            label = str(dates[idx_val])
        x_labels += f'<text x="{x}" y="{h - 5}" text-anchor="middle" font-size="11" fill="#6c757d">{label}</text>'

    return f"""<section class="chart-section">
<h2>Weight History (Top {top_n} Positions)</h2>
<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg">
{y_labels}
{x_labels}
{areas}
{legend}
</svg>
</section>"""


def _html_escape(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )
